// ALERT
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

// AUTH
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOG_OUT = "LOG_OUT";

export const DELETE_ACCOUNT = "DELETE_ACCOUNT";

// PROFILE
export const GET_PET_PROFILE = "GET_PET_PROFILE";
export const PET_PROFILE_ERROR = "PET_PROFILE_ERROR";
export const CLEAR_PET_PROFILE = "CLEAR_PET_PROFILE";
export const PUT_PET_PROFILE = "PUT_PET_PROFILE";
export const CLOSE_PET_PROFILE_MODAL = "CLOSE_PET_PROFILE_MODAL";
export const OPEN_PET_PROFILE_MODAL = "OPEN_PET_PROFILE_MODAL";
export const PUT_LOOKFOR_PROFILE_INFO = "PUT_LOOKFOR_PROFILE_INFO";
export const GET_ALL_PET_PROFILES = "GET_ALL_PET_PROFILES";
export const GET_PET_PROFILE_BY_ID = "GET_PET_PROFILE_BY_ID";
export const UPDATE_PET_PROFILE_LIKES = "UPDATE_PET_PROFILE_LIKES";

// POST
export const GET_POST = "GET_POST";
export const GET_POSTS = "GET_POSTS";
export const POST_ERROR = "POST_ERROR";
export const ADD_POST = "ADD_POST";
export const DELETE_POST = "DELETE_POST";
export const UPDATE_POST_LIKES = "UPDATE_POST_LIKES";

// COMMENT
export const ADD_COMMENT = "ADD_COMMENT";
export const REMOVE_COMMENT = "REMOVE_COMMENT";
