// ALERT
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

// AUTH
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOG_OUT = "LOG_OUT";

export const DELETE_ACCOUNT = "DELETE_ACCOUNT";

// PROFILE
export const GET_PET_PROFILE = "GET_PET_PROFILE";
export const PET_PROFILE_ERROR = "PET_PROFILE_ERROR";
export const CLEAR_PET_PROFILE = "CLEAR_PET_PROFILE";
export const PUT_PET_PROFILE = "PUT_PET_PROFILE";
export const CLOSE_PET_PROFILE_MODAL = "CLOSE_PET_PROFILE_MODAL";
export const OPEN_PET_PROFILE_MODAL = "OPEN_PET_PROFILE_MODAL";
export const PUT_LOOKFOR_PROFILE_INFO = "PUT_LOOKFOR_PROFILE_INFO";
